### PR TITLE
Adding Younies Mahmoud (YMD)

### PR DESCRIPTION
**Pull request by rricard**

### CODE REVIEW

**Comment by mpcsh** [comment]
@younies we went with `YMD` by default. are you okay with this or would you like to use a different abbreviation?

**Comment by rricard** [comment]
@younies can you check if you want to appear as YMD in the notes. Thanks!

**Comment by sffc** [comment]
YMD is also what we used in February and what we use in ECMA-402.

**Review by younies — APPROVED** [review]

**Comment by younies** [comment]
thanks :)

**Pull request merged**
