### PR TITLE
Add @brainkim initials (BRK) to notes/delegates.txt

### PR DESCRIPTION
**Pull request by benjamn**
Brian Kim is an employee of ECMA member organization [Apollo Graph, Inc](https://www.apollographql.com/), formerly named Meteor Development Group, joining Ben Newman (@benjamn).

Not sure who exactly I should flag for review, so please feel free to @-mention others if you know better!

### CODE REVIEW

**Comment by ljharb** [comment]
@benjamn have you filed an onboarding issue on https://github.com/tc39/Admin-and-Business/issues ?

**Comment by benjamn** [comment]
@ljharb Yes! https://github.com/tc39/Admin-and-Business/issues/153

**Comment by chazjeremyrosette** [comment]
add-@brainkim-delegate-initialsto fund chazrosette@gmail.com from cashapl

**Review by robpalme — APPROVED** [review]

**Comment by benjamn** [comment]
Thanks @robpalme!

**Pull request merged**
