### PR TITLE
Add Eric Leese (ESL)

### PR DESCRIPTION
**Pull request by syg**

### CODE REVIEW

**Comment by ctcpip** [comment]
@EricSL Would you consider `ELE` to match others?

**Comment by syg** [comment]
> @EricSL Would you consider ELE to match others?

What's wrong with ESL?

**Comment by ctcpip** [comment]
when available, conventionally the TLA should be first letter of first name, first letter of last name, last letter of last name.

**Comment by syg** [comment]
I am not aware that we had a convention we tried to follow. I am also not in favor of following a convention. We ask delegates for their preference, and if there's no conflict, we should honor their preference.

**Comment by ctcpip** [comment]
it's not a hard requirement, just where we steer when available.  nothing wrong with ESL

**Review by ctcpip — APPROVED** [review]

**Pull request merged**
