### PR TITLE
Add myself to delegates (from Sujitech)

### PR DESCRIPTION
**Pull request by Jack-Works**

### CODE REVIEW

**Comment by Jack-Works** [comment]
@codehag hello

**Comment by codehag** [comment]
Hi Jack, since we have so many participants, the convention for new members is to use a three letter acronym. The pattern is first letter of first name, first letter of last name, last letter of last name. If for example you use "Jack Works", it would be "JWS". We usually do not use pseudonyms however, so it would be great to have your english working name here.

**Comment by codehag** [comment]
At the moment, a lot of people are on holidays -- it may take some time for this to be merged. There should be more activity starting January 2nd.

**Comment by codehag** [comment]
Hi, it looks like there is still an issue. Jason Williams has the acronym (JWS), so you will need to use something else. 

You can see the checks here: https://github.com/tc39/notes/blob/master/scripts/check-delegates.js

**Comment by Jack-Works** [comment]
I have changed to JWK

**Pull request merged**
