### PR TITLE
Add Edgar Barragan (EDB)

### PR DESCRIPTION
**Pull request by robpalme**

### CODE REVIEW

**Comment by msaboff** [comment]
What is the status of adding Edgar as a delegate?  Do we need some more info?

**Comment by ljharb** [comment]
@msaboff i think the PR might have been waiting for your stamp

**Comment by msaboff** [comment]
I'm fine with this addition.  Go ahead and add Edgar.

**Review by msaboff — APPROVED** [review]
LGTM

**Comment by ljharb** [comment]
@robpalme i think we're supposed to be doing 3-char abbreviations for all new additions

**Comment by msaboff** [comment]
Change the abbreviation to EDB.

**Pull request merged**
