### PR TITLE
Add Pablo Gorostiaga Belio (PGB)

### PR DESCRIPTION
**Pull request by littledan**

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Comment by ctcpip** [comment]
`PBO` is the preferred convention.  can we use that instead?  @littledan

**Comment by ljharb** [comment]
oh right, good call

**Comment by ctcpip** [comment]
> `PBO` is the preferred convention.

resolved by https://github.com/tc39/notes/pull/274

**Comment by ctcpip** [comment]
@gorosgobe Would you consider `PGO` or `PBO` to match others?

**Comment by gorosgobe** [comment]
@ctcpip I don't mind either, but if we follow the convention of first and last letters of the last name, then it should be `PGO` - my last name is "Gorostiaga Belio"

**Comment by ctcpip** [comment]
similar to me with `CDA` :)

**Pull request merged**
