### PR TITLE
104th Meeting of TC39, notes

### PR DESCRIPTION
**Pull request by gesa**
Great job with summaries and conclusions everyone. Just a few more to go.

**Missing Speaker Summaries and Conclusions:**

- Day 1
  - @ben-allen on "3 Normative PRs"
  - @syg JS0/jsSugar
- Day 2
  - @ljharb Error.isError
  - @ben-allen Normative: Allow use of non-ISO 4217 data in CurrencyDigits AO
- Day 3
  - @syg on js0/jsSugar

### CODE REVIEW

**Comment by ctcpip** [comment]
I'm guessing we probably aren't in the habit of doing this, but we should move continuations to be colocated with the original topics.  Otherwise, they may end up sort of lost because people looking at the notes have no indication that the topic continued later and there are more notes.  

cc @tc39/chairs

**Comment by michaelficarra** [comment]
@ctcpip I'd prefer to leave them in place and have the notes be an accurate recording of events. What do you think about just putting a link to the continuation at the end of any continued topic?

**Comment by ctcpip** [comment]
@michaelficarra it's not my preference, but would be an acceptable compromise

**Comment by gesa** [comment]
@tc39/chairs no longer in draft, merge at will.

**Review by ryzokuken — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
Hey, I had https://github.com/gesa/tc39-notes/pull/1 that got missed (GitHub gave me a permission error when I tried to push directly to this PR)

**Comment by ryzokuken** [comment]
@nicolo-ribaudo can you make a PR to this repo instead?

**Pull request merged**
