### PR TITLE
Add Caroline Cullen to delegates

### PR DESCRIPTION
**Pull request by codehag**
@carolinecullen to check

### CODE REVIEW

**Review by MylesBorins — APPROVED** [review]
LGTM

**Comment by MylesBorins** [comment]
@carolinecullen are you OK with the chosen abbreviation here?

**Comment by gesa** [comment]
ping @carolinecullen, could you approve this PR for identifying you in our notes as `CCU`

**Comment by carolinecullen** [comment]
Im fine with CCU for my notes. Thanks!

**Pull request merged**
